(function(){
  const API='https://tq93-suggestions-service.akmoldaev-akhat.chatgpt.site';
  const fileTypes='image/jpeg,image/png,image/webp,image/heic,application/pdf,.doc,.docx,.xls,.xlsx';
  const previousHome=home;let authorCode='';
  const statusClass=s=>s==='Қарастырылуда'?'warn':s==='Қабылданбады'?'bad':s==='Жауап берілді'||s==='Қабылданды'?'good':'';
  const dateText=v=>v?new Date(v).toLocaleString('kk-KZ',{dateStyle:'medium',timeStyle:'short'}):'—';
  const size=v=>v<1048576?`${Math.ceil(v/1024)} КБ`:`${(v/1048576).toFixed(1)} МБ`;
  const files=items=>(items||[]).length?`<div class="suggestion-files"><b>Тіркелген файлдар</b>${items.map(x=>`<a href="${API}${esc(x.url)}" target="_blank" rel="noopener">📎 ${esc(x.filename)} <small>(${size(Number(x.size_bytes)||0)})</small></a>`).join('')}</div>`:'';

  home=function(){if(user?.role==='author')return openAuthorSuggestions();previousHome();if(!user)return;const a=[...document.querySelectorAll('#app h2')].find(x=>x.textContent.trim()==='Назар аудару');if(a)a.insertAdjacentHTML('beforebegin',`<button class="secondary wide suggestion-button" type="button" onclick="openSuggestionForm()"><span><strong>Авторға ұсыныс</strong><small>Идея, ескерту немесе қосымша функция ұсыну</small></span><span class="suggestion-icon">✉</span></button>`)};

  window.openSuggestionForm=function(){if(!user||user.role==='author')return;shell(`<button class="secondary" onclick="go('home')">← Басты бет</button><h1>Авторға ұсыныс</h1><p class="muted">Ұсыныс авторға ортақ журналда бірден көрінеді.</p><form id="suggestionForm"><section class="card"><label>Тақырыбы<input name="subject" maxlength="100" placeholder="Мысалы: обход бөлімін ыңғайландыру" required /></label><label>Ұсыныс немесе ескерту<textarea name="message" maxlength="1500" placeholder="Не өзгерту керек екенін жазыңыз…" required></textarea></label><label>Фото немесе құжат тіркеу<input id="suggestionFiles" type="file" accept="${fileTypes}" multiple /><small class="muted">3 файлға дейін: фото, PDF, Word немесе Excel. Әр файл 8 МБ-тан аспасын.</small></label><label>Жауап алатын байланыс<input name="contact" maxlength="120" placeholder="Email немесе телефон нөмірі" required /></label><p class="suggestion-contact">Автор жауапты осы байланысқа жібереді және ол төменде де көрінеді.</p></section><button class="good wide" type="button" onclick="sendSuggestion()">Ұсынысты жіберу</button></form><h2>Менің ұсыныстарым</h2><div id="mySuggestions" class="empty">Жүктелуде…</div>`);loadMySuggestions()};

  window.sendSuggestion=async function(){const form=document.querySelector('#suggestionForm');if(!form||!form.reportValidity())return;const selected=[...(document.querySelector('#suggestionFiles')?.files||[])];if(selected.length>3){alert('Бір ұсынысқа 3 файлдан артық тіркеуге болмайды.');return}if(selected.some(f=>f.size>8*1024*1024)){alert('Әр файлдың көлемі 8 МБ-тан аспауы керек.');return}const data=new FormData(form),button=form.querySelector('button');button.disabled=true;button.textContent='Жіберілуде…';try{const response=await fetch(`${API}/api/suggestions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({facility:user.facility,operatorName:user.name,operatorTabNo:user.tabNo,subject:data.get('subject'),message:data.get('message'),contact:data.get('contact')})}),result=await response.json();if(!response.ok)throw new Error(result.error||'Ұсыныс жіберілмеді.');for(let i=0;i<selected.length;i++){button.textContent=`Файл жүктелуде… ${i+1}/${selected.length}`;const upload=new FormData();upload.append('tabNo',user.tabNo);upload.append('file',selected[i]);const up=await fetch(`${API}/api/suggestions/${encodeURIComponent(result.id)}/attachments`,{method:'POST',body:upload}),answer=await up.json();if(!up.ok)throw new Error(answer.error||'Файл жүктелмеді.')}form.reset();alert('Ұсыныс жіберілді. Статусын осы беттен қарай аласыз.');loadMySuggestions()}catch(error){alert(error.message||'Желіге қосылу мүмкін болмады.')}finally{button.disabled=false;button.textContent='Ұсынысты жіберу'}};

  async function loadMySuggestions(){const target=document.querySelector('#mySuggestions');if(!target||!user)return;try{const r=await fetch(`${API}/api/suggestions?tabNo=${encodeURIComponent(user.tabNo)}`),data=await r.json();if(!r.ok)throw new Error();target.className='';target.innerHTML=(data.items||[]).map(item=>`<section class="card suggestion-record"><div class="row"><b>${esc(item.subject)}</b><span class="pill ${statusClass(item.status)}">${esc(item.status)}</span></div><small class="muted">${dateText(item.created_at)}</small><p>${esc(item.message)}</p>${files(item.attachments)}${item.author_response?`<div class="suggestion-response"><b>Автор жауабы</b><br>${esc(item.author_response)}<br><small>${dateText(item.responded_at)}</small></div>`:''}</section>`).join('')||'<div class="empty">Әзірге ұсыныс жіберілмеген.</div>'}catch{target.className='notice';target.textContent='Ұсыныстар журналына қосылу мүмкін болмады.'}};

  window.openAuthorSuggestions=function(){if(!user||user.role!=='author')return;shell(`<button class="secondary" onclick="signOut()">← Шығу</button><h1>Ұсыныстар</h1><p class="muted">Операторлар мен шеберлер жіберген ұсыныстарға статус пен жауап енгізіңіз.</p><section class="card author-access"><label>Автор коды<input id="authorCode" type="password" placeholder="Автор кодын енгізіңіз" /></label><button class="wide" type="button" onclick="loadAuthorSuggestions()">Ұсыныстарды ашу</button></section><div id="authorSuggestions"></div>`)};

  window.loadAuthorSuggestions=async function(){const code=document.querySelector('#authorCode');authorCode=code?.value.trim()||authorCode;const target=document.querySelector('#authorSuggestions');if(!authorCode){alert('Автор кодын енгізіңіз.');return}target.innerHTML='<div class="empty">Жүктелуде…</div>';try{const r=await fetch(`${API}/api/author/suggestions`,{headers:{'x-author-code':authorCode}}),data=await r.json();if(!r.ok)throw new Error(data.error||'Жүктелмеді.');target.innerHTML=(data.items||[]).map((item,i)=>`<section class="card author-suggestion"><div class="row"><b>${esc(item.subject)}</b><span class="pill ${statusClass(item.status)}">${esc(item.status)}</span></div><p class="muted">${esc(item.operator_name)} · табель №${esc(item.operator_tab_no)}<br>${esc(item.facility)} · ${dateText(item.created_at)}<br>Байланыс: ${esc(item.contact)}</p><p>${esc(item.message)}</p>${files(item.attachments)}<label>Статус<select id="suggestionStatus${i}">${['Жаңа','Қарастырылуда','Жауап берілді','Қабылданды','Қабылданбады'].map(s=>`<option ${s===item.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Автор жауабы<textarea id="suggestionResponse${i}" maxlength="1500" placeholder="Операторға берілетін жауап">${esc(item.author_response||'')}</textarea></label><button class="good wide" type="button" onclick="saveAuthorSuggestion('${esc(item.id)}',${i})">Өзгерісті сақтау</button></section>`).join('')||'<div class="empty">Ұсыныстар әзірге жоқ.</div>'}catch(error){target.innerHTML=`<div class="notice">${esc(error.message||'Ұсыныстар журналын ашу мүмкін болмады.')}</div>`}};

  window.saveAuthorSuggestion=async function(id,i){const status=document.querySelector(`#suggestionStatus${i}`)?.value,authorResponse=document.querySelector(`#suggestionResponse${i}`)?.value;try{const r=await fetch(`${API}/api/author/suggestions/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'content-type':'application/json','x-author-code':authorCode},body:JSON.stringify({status,authorResponse})}),data=await r.json();if(!r.ok)throw new Error(data.error||'Сақталмады.');alert('Өзгеріс сақталды.');loadAuthorSuggestions()}catch(error){alert(error.message||'Өзгерісті сақтау мүмкін болмады.')}};
})();
